install: true

sudo: false

services:
  - docker

before_script:
  - git checkout $TRAVIS_BRANCH

script:
  - docker build -t appdax/bb-fetcher:test -f Dockerfile.test .
  - docker run -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN -t appdax/bb-fetcher:test
  - docker rmi -f appdax/bb-fetcher:test
  - docker ps -a
  - docker images --filter "dangling=false"
